# OpenClinica Service

# Postgres
ocpg:
  net: "common"
  build: ./postgres
  env_file:
    - ./docker-envs.env
  volumes_from:
    - ocpgfiles

# OpenClinica Webapp
ocweb:
  net: "common"
  build: ./tomcat
  dockerfile: Dockerfile-web
  env_file:
    - ./docker-envs.env
  volumes_from:
    - ocwebfiles
# Uncomment for "basic" deployment
#  ports:
#    - "8080:8080"

# OpenClinica Webservice
ocws:
  net: "common"
  build: ./tomcat
  dockerfile: Dockerfile-ws
  env_file:
    - ./docker-envs.env
  volumes_from:
    - ocwsfiles
# Uncomment for "basic" deployment
#  ports:
#    - "8081:8080"

# Data Containers
ocpgfiles:
  net: "none"
  image: busybox
  volumes:
    - /var/lib/postgresql/data
ocwebfiles:
  net: "none"
  image: busybox
  volumes:
    - /usr/local/tomcat/logs
    - /usr/local/tomcat/ocdata
ocwsfiles:
  net: "none"
  image: busybox
  volumes:
    - /usr/local/tomcat/logs
    - /usr/local/tomcat/ocdata